# Input and output tasks
in_domains: Sat_RGB-UAV_RGB
out_domains: Sat_RGB-UAV_RGB
standardize_depth: True
extra_norm_pix_loss: True

# Architecture
model: pretrain_multimae_base
decoder_dim: 256
input_size: 224
patch_size: 16
alphas: 1  # Dirichlet concentration parameter
num_encoded_tokens: 196 # Total would be 196 * 3 patches. 196 / 2 = 98
num_global_tokens: 1
decoder_use_task_queries: True
decoder_depth: 2

# Train
epochs: 0
opt: adamw
blr: 0.0001 # this is base_lr = 1e-4, lr = base_lr * batch_size / 256
warmup_lr: 0.000001 # 1e-6
min_lr: 0.
warmup_epochs: 40
batch_size: 128
hflip: 0.5
loss_on_unmasked: False
# fp32_output_adapters: semseg

# Data
data_path: ''  


# Wandb logging
log_wandb: False # Set to True to log to Weights & Biases
wandb_project: 'Sat-UAV'
wandb_entity: null # Change if needed
wandb_run_name: "tif_Amesall_ep300"
output_dir: 'pretrain/sat_uav/' # Change directory if needed
